apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-mongo-pv
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/home/k8svolumes/my-mongo-pv"